- retrieved: '2026-10-07'
  url: https://www.nyc.gov/site/hra/help/snap-application-frequently-asked-questions.page
  final_url: https://www.nyc.gov/site/hra/help/snap-application-frequently-asked-questions.page
  status: 200
  content_type: text/html;charset=utf-8
  text_sha256: a00f3de1aa40f7443bf1c006214582637038f676494ba74d8f50c3c80330eb87
  text: ny-hra-snap-faq/2026-10-07.txt
  raw: ny-hra-snap-faq/2026-10-07.html
