- retrieved: '2026-10-07'
  url: https://newyork.public.law/laws/n.y._education_law_section_915-a
  final_url: https://newyork.public.law/laws/n.y._education_law_section_915-a
  status: 200
  content_type: text/html; charset=utf-8
  text_sha256: 82ae01f6d75d217069d352cab8667b0c9b218a11c81ae048dbdfc285e09a9a6d
  text: ny-edn-915-a-publiclaw/2026-10-07.txt
  raw: ny-edn-915-a-publiclaw/2026-10-07.html
