- retrieved: '2026-10-07'
  url: https://www.cdss.ca.gov/Portals/9/Additional-Resources/Letters-and-Notices/ACLs/2025/25-92.pdf
  final_url: https://www.cdss.ca.gov/Portals/9/Additional-Resources/Letters-and-Notices/ACLs/2025/25-92.pdf
  status: 200
  content_type: application/pdf
  text_sha256: 2dc0b520732054c76ca938709fa55cf5989c7536269a0cb8e68e4c6a9d30198a
  text: ca-acl-25-92/2026-10-07.txt
  raw: ca-acl-25-92/2026-10-07.pdf
