- retrieved: '2026-10-07'
  url: https://www.cdss.ca.gov/Portals/9/Additional-Resources/Letters-and-Notices/ACLs/2026/26-04.pdf
  final_url: https://www.cdss.ca.gov/Portals/9/Additional-Resources/Letters-and-Notices/ACLs/2026/26-04.pdf
  status: 200
  content_type: application/pdf
  text_sha256: 1398c5c4c81eb3e2de0e51b5c6514752a33214f72e47ed60c884102295e23365
  text: ca-acl-26-04/2026-10-07.txt
  raw: ca-acl-26-04/2026-10-07.pdf
