- retrieved: '2026-10-07'
  url: https://www.isbe.net/Lists/News/DispForm.aspx?ID=1599
  final_url: https://www.isbe.net/Lists/News/DispForm.aspx?ID=1599
  status: 200
  content_type: text/html; charset=utf-8
  text_sha256: 34deddcb9487b82c5738dbccb0906089d5f64361ae1644edca8202a88dc7b65f
  text: il-isbe-ieg-release-2026/2026-10-07.txt
  raw: il-isbe-ieg-release-2026/2026-10-07.html
