- retrieved: '2026-10-07'
  url: https://www.law.cornell.edu/regulations/new-york/18-NYCRR-387.17
  final_url: https://www.law.cornell.edu/regulations/new-york/18-NYCRR-387.17
  status: 200
  content_type: text/html; charset=utf-8
  text_sha256: f0b70550f529c02d3c3239c986d1c456914b3583ae54da2ae88a6eaa8f54798c
  text: ny-nycrr-387-17-lii/2026-10-07.txt
  raw: ny-nycrr-387-17-lii/2026-10-07.html
