- retrieved: '2026-10-07'
  url: https://www.dhs.state.il.us/page.aspx?item=14898
  final_url: https://www.dhs.state.il.us/page.aspx?item=14898
  status: 200
  content_type: text/html; charset=utf-8
  text_sha256: 90b52cdaa4de80a3ff381bb4f5088389e5b02abda6bcbce439ee52ab6adadf89
  text: il-idhs-pm-07-02-05/2026-10-07.txt
  raw: il-idhs-pm-07-02-05/2026-10-07.html
