- retrieved: '2026-10-07'
  url: https://www.law.cornell.edu/regulations/illinois/IL-Admin-Code-89-121-63
  final_url: https://www.law.cornell.edu/regulations/illinois/IL-Admin-Code-89-121-63
  status: 200
  content_type: text/html; charset=utf-8
  text_sha256: c404536b278888cb8d24573f3b6863e03ccfe019aec46656508f7334094104f7
  text: il-admin-code-89-121-63-lii/2026-10-07.txt
  raw: il-admin-code-89-121-63-lii/2026-10-07.html
