import { randomUUID } from 'node:crypto';
import { WebSocket } from 'ws';
import { z } from 'zod';
import { PORTALS } from './connectors.js';

const httpsUrl = z.url().refine(s => {
  const u = new URL(s);
  return u.protocol === 'https:' && !u.username && !u.password && !u.search && !u.hash;
}, 'Use a fixed HTTPS URL without credentials, query or fragment');
const field = z.object({ selector: z.string().min(1).max(300), attribute: z.string().regex(/^data-[a-z-]+$/).optional() }).strict();
/** Operator-reviewed portal rules, never generated by the conversation model.
 * Account ID must be a stable provider identifier, not a greeting/display name. */
export const portalPolicySchema = z.object({
  id: z.enum(PORTALS.map(p => p.id)), revision: z.string().min(1).max(80),
  loginUrl: httpsUrl, readUrl: httpsUrl,
  signedOutSelector: z.string().min(1).max(300), accountId: field, accountLabel: field,
  fields: z.array(field.extend({ label: z.string().min(1).max(80) }).strict()).min(1).max(8),
}).strict();
export type PortalPolicy = z.infer<typeof portalPolicySchema>;
/** Bring-up can capture a human-controlled session before account selectors are
 * validated. It grants no automated read or action capability. */
export const portalAccessPolicySchema = z.union([portalPolicySchema, z.object({
  mode: z.literal('login_only'), id: z.enum(PORTALS.map(p => p.id)),
  revision: z.string().min(1).max(80), loginUrl: httpsUrl,
}).strict()]);
export type PortalAccessPolicy = z.infer<typeof portalAccessPolicySchema>;
export interface PortalSnapshot {
  accountId: string; accountLabel: string; fields: Array<{ label: string; value: string }>;
  source: string; observedAt: string; policyRevision: string;
}
export interface BrowserSession { id: string }
export interface SkyvernBrowser {
  create(url: string, profile?: string): Promise<BrowserSession>;
  viewable(session: string): Promise<boolean>;
  close(session: string): Promise<void>;
  save(session: string, name: string): Promise<string | undefined>;
  remove(profile: string): Promise<void>;
  findProfile(name: string): Promise<string | undefined>;
  snapshot(session: string, policy: PortalPolicy, expectedAccountId?: string): Promise<PortalSnapshot>;
  viewer(session: string): string;
}

export class SkyvernRequestError extends Error {
  constructor(readonly status?: number, readonly session?: string) { super('Skyvern request unavailable'); }
}

/** No dotenv, browser-agent prompts, screenshots, arbitrary tasks or write tools.
 * The only site interaction we automate is a fixed read URL and passive DOM reads.
 * Vendor-side recording/retention is a deployment/contract setting, not an invented API flag. */
export class SkyvernBrowserClient implements SkyvernBrowser {
  constructor(private readonly key: string, private readonly request = fetch, private readonly navigate = navigateBrowser) {
    if (!key) throw new Error('Skyvern API key required');
  }
  private async api(path: string, method = 'GET', body?: unknown): Promise<any> {
    try {
      const r = await this.request(`https://api.skyvern.com${path}`, { method,
        headers: { 'x-api-key': this.key, 'Content-Type': 'application/json' },
        body: body === undefined ? undefined : JSON.stringify(body), redirect: 'error', signal: AbortSignal.timeout(15_000) });
      if (!r.ok) { await r.body?.cancel(); throw new SkyvernRequestError(r.status); }
      return r.status === 204 ? undefined : await r.json();
    } catch (e) { if (e instanceof SkyvernRequestError) throw e; throw new SkyvernRequestError(); }
  }
  async create(url: string, profile?: string): Promise<BrowserSession> {
    if (!httpsUrl.safeParse(url).success) throw new SkyvernRequestError();
    const r = await this.api('/v1/browser_sessions', 'POST', {
      timeout: 10, generate_browser_profile: true, needs_live_view: !profile,
      ...(profile ? { browser_profile_id: profile } : {}),
    });
    if (!/^pbs_[A-Za-z0-9_-]+$/.test(r?.browser_session_id)) throw new SkyvernRequestError();
    const id: string = r.browser_session_id;
    try {
      // Session creation does not navigate, even when a URL is supplied to the API.
      await this.navigate(await this.address(id), this.headers(id), url);
      return { id };
    } catch {
      // Preserve the resource for the durable cleanup queue. Never recreate it
      // merely because CDP navigation or endpoint discovery failed.
      throw new SkyvernRequestError(undefined, id);
    }
  }
  private id(id: string, prefix: string): string {
    if (!new RegExp(`^${prefix}_[A-Za-z0-9_-]+$`).test(id)) throw new SkyvernRequestError();
    return id;
  }
  async session(session: string) {
    return this.api(`/v1/browser_sessions/${this.id(session, 'pbs')}`);
  }
  async viewable(session: string): Promise<boolean> {
    const r = await this.session(session);
    return r?.status === 'running' && r.stream_transport === 'vnc' && r.vnc_streaming_supported === true;
  }
  async close(session: string): Promise<void> {
    const id = this.id(session, 'pbs');
    try {
      const state = await this.session(id);
      if (state?.status === 'closed' || state?.status === 'completed') return;
      await this.api(`/v1/browser_sessions/${id}/close`, 'POST');
    } catch (e) { if (!(e instanceof SkyvernRequestError && e.status === 404)) throw e; }
  }
  async findProfile(name: string): Promise<string | undefined> {
    const rows = await this.api(`/v1/browser_profiles?search_key=${encodeURIComponent(name)}&managed=false`);
    if (!Array.isArray(rows)) throw new SkyvernRequestError();
    const matches = rows.filter(p => p.name === name);
    if (matches.length > 1) throw new SkyvernRequestError();
    return matches[0] ? this.id(matches[0].browser_profile_id, 'bp') : undefined;
  }
  async save(session: string, name: string): Promise<string | undefined> {
    // Stable, organization-unique name reconciles a lost create response. Never
    // make up a new name on retry; 400 can mean the closed-session archive isn't ready.
    const existing = await this.findProfile(name);
    if (existing) return existing;
    try {
      const p = await this.api('/v1/browser_profiles', 'POST', { name, browser_session_id: this.id(session, 'pbs') });
      return this.id(p?.browser_profile_id, 'bp');
    } catch (e) {
      if (e instanceof SkyvernRequestError && [400, 409].includes(e.status!)) return;
      throw e;
    }
  }
  async remove(profile: string): Promise<void> {
    try { await this.api(`/v1/browser_profiles/${this.id(profile, 'bp')}`, 'DELETE'); }
    catch (e) { if (!(e instanceof SkyvernRequestError && e.status === 404)) throw e; }
  }
  viewer(session: string): string {
    return `wss://api.skyvern.com/v1/stream/vnc/browser_session/${this.id(session, 'pbs')}?apikey=${encodeURIComponent(this.key)}&client_id=${randomUUID()}`;
  }
  private headers(session: string): Record<string, string> {
    return { 'x-api-key': this.key, 'X-Session-Id': session };
  }
  private async address(session: string): Promise<string> {
    const r = await this.session(session);
    if (r?.status !== 'running' || typeof r.browser_address !== 'string') throw new SkyvernRequestError();
    const url = new URL(r.browser_address);
    // Never forward our API key to an arbitrary CDP endpoint supplied in a response.
    if (url.protocol !== 'wss:' || url.username || url.password ||
      (url.hostname !== 'api.skyvern.com' && !url.hostname.endsWith('.skyvern.com'))) throw new SkyvernRequestError();
    return url.href;
  }
  async snapshot(session: string, policy: PortalPolicy, expectedAccountId?: string): Promise<PortalSnapshot> {
    return passiveSnapshot(await this.address(session), this.headers(session), policy, expectedAccountId);
  }
}

type CdpCall = (method: string, params?: unknown, sessionId?: string) => Promise<any>;
async function withCdp<T>(address: string, headers: Record<string, string>, work: (call: CdpCall) => Promise<T>): Promise<T> {
  const ws = new WebSocket(address, { headers, handshakeTimeout: 5000, maxPayload: 1024 * 1024 });
  const pending = new Map<number, { resolve: (value: any) => void; reject: () => void }>();
  let sequence = 0;
  const fail = () => { for (const p of pending.values()) p.reject(); pending.clear(); };
  const timer = setTimeout(() => { fail(); ws.terminate(); }, 12_000);
  ws.on('error', fail); ws.on('close', fail);
  ws.on('message', bytes => {
    try {
      const r = JSON.parse(bytes.toString()); const p = pending.get(r.id);
      if (p) { pending.delete(r.id); r.error ? p.reject() : p.resolve(r.result); }
    } catch { fail(); ws.terminate(); }
  });
  const call = (method: string, params: unknown = {}, sessionId?: string) => new Promise<any>((resolve, reject) => {
    const id = ++sequence; pending.set(id, { resolve, reject: () => reject(new SkyvernRequestError()) });
    ws.send(JSON.stringify({ id, method, params, ...(sessionId ? { sessionId } : {}) }));
  });
  try {
    await new Promise<void>((resolve, reject) => {
      ws.once('open', resolve); ws.once('error', () => reject(new SkyvernRequestError())); ws.once('close', () => reject(new SkyvernRequestError()));
    });
    return await work(call);
  } finally { clearTimeout(timer); fail(); ws.terminate(); }
}

/** Navigate one unambiguous page to the operator-reviewed URL; no form actions. */
export async function navigateBrowser(address: string, headers: Record<string, string>, url: string): Promise<void> {
  if (!httpsUrl.safeParse(url).success) throw new SkyvernRequestError();
  await withCdp(address, headers, async call => {
    const { targetInfos } = await call('Target.getTargets');
    const pages = targetInfos.filter((t: any) => t.type === 'page');
    if (pages.length !== 1) throw new SkyvernRequestError();
    const { sessionId } = await call('Target.attachToTarget', { targetId: pages[0].targetId, flatten: true });
    const result = await call('Page.navigate', { url }, sessionId);
    if (result.errorText || result.isDownload) throw new SkyvernRequestError();
  });
}

/** Fixed CDP commands. No clicks, form writes, model-generated JS or navigation.
 * throwOnSideEffect refuses page monkeypatches that would mutate state during evaluation. */
export async function passiveSnapshot(address: string, headers: Record<string, string>, policy: PortalPolicy, expectedAccountId?: string): Promise<PortalSnapshot> {
  return withCdp(address, headers, async call => {
    const expected = new URL(policy.readUrl);
    const { targetInfos } = await call('Target.getTargets');
    const targets = targetInfos.filter((t: any) => {
      try { const u = new URL(t.url); return t.type === 'page' && u.origin === expected.origin && u.pathname === expected.pathname; }
      catch { return false; }
    });
    if (targets.length !== 1) throw new SkyvernRequestError();
    const { sessionId } = await call('Target.attachToTarget', { targetId: targets[0].targetId, flatten: true });
    const expression = `(() => {
      const p = ${JSON.stringify(policy)};
      const read = f => {
        const nodes = document.querySelectorAll(f.selector);
        if (nodes.length !== 1) throw new Error('Ambiguous field');
        const value = (f.attribute ? nodes[0].getAttribute(f.attribute) : nodes[0].textContent)?.trim();
        if (!value || value.length > 300) throw new Error('Missing or oversized field');
        return value;
      };
      if (document.querySelector(p.signedOutSelector)) throw new Error('Sign-in required');
      const accountId = read(p.accountId);
      const expectedAccountId = ${JSON.stringify(expectedAccountId ?? null)};
      if (expectedAccountId !== null && accountId !== expectedAccountId) throw new Error('Account changed');
      return { source: location.origin + location.pathname, accountId,
        accountLabel: read(p.accountLabel), fields: p.fields.map(f => ({ label: f.label, value: read(f) })) };
    })()`;
    const r = await call('Runtime.evaluate', { expression, returnByValue: true, throwOnSideEffect: true, timeout: 5000 }, sessionId);
    if (r.exceptionDetails || r.result?.value?.source !== expected.origin + expected.pathname) throw new SkyvernRequestError();
    const value = z.object({ source: z.string(), accountId: z.string().min(1).max(200), accountLabel: z.string().min(1).max(200),
      fields: z.array(z.object({ label: z.string().max(80), value: z.string().min(1).max(300) }).strict()).max(8),
    }).strict().parse(r.result.value);
    if (value.fields.length !== policy.fields.length || value.fields.some((f, i) => f.label !== policy.fields[i]!.label)) throw new SkyvernRequestError();
    return { ...value, observedAt: new Date().toISOString(), policyRevision: policy.revision };
  });
}
