- retrieved: '2026-10-07'
  url: https://www.cdss.ca.gov/Portals/9/Additional-Resources/Letters-and-Notices/ACINs/2026/I-40_26.pdf
  final_url: https://www.cdss.ca.gov/Portals/9/Additional-Resources/Letters-and-Notices/ACINs/2026/I-40_26.pdf
  status: 200
  content_type: application/pdf
  text_sha256: 76fbb6c75278b2a5ebacc8b959034e31fb6b30fb0d73fec82312c52eaeda9de2
  text: ca-acin-i-40-26/2026-10-07.txt
  raw: ca-acin-i-40-26/2026-10-07.pdf
