- retrieved: '2026-10-07'
  url: https://www.law.cornell.edu/regulations/new-york/18-NYCRR-387.12
  final_url: https://www.law.cornell.edu/regulations/new-york/18-NYCRR-387.12
  status: 200
  content_type: text/html; charset=utf-8
  text_sha256: a5744f5f374341c3ae2915a3e32a8f1bde09724fd1a60769ac25612a93cbf740
  text: ny-nycrr-387-12-lii/2026-10-07.txt
  raw: ny-nycrr-387-12-lii/2026-10-07.html
