- retrieved: '2026-10-07'
  url: https://hfs.illinois.gov/info/brochures-and-forms/brochures/hfs3352.html
  final_url: https://hfs.illinois.gov/info/brochures-and-forms/brochures/hfs3352.html
  status: 200
  content_type: text/html;charset=utf-8
  text_sha256: 82b4c087b3b3ecd4f4e0e412aa8513c22337440ef8da272e2bb0e68486e58d33
  text: il-hfs-3352/2026-10-07.txt
  raw: il-hfs-3352/2026-10-07.html
