- retrieved: '2026-10-07'
  url: https://hfs.illinois.gov/content/dam/soi/en/web/hfs/sitecollectiondocuments/abepartnerportalforltc.pdf
  final_url: https://hfs.illinois.gov/content/dam/soi/en/web/hfs/sitecollectiondocuments/abepartnerportalforltc.pdf
  status: 200
  content_type: application/pdf
  text_sha256: cd2e7f17f132ffc8470b8075e3b2e4490c8f17c2e877d1d435329bb357c6f975
  text: il-hfs-abe-ltc-partner-portal/2026-10-07.txt
  raw: il-hfs-abe-ltc-partner-portal/2026-10-07.pdf
