- retrieved: '2026-10-07'
  url: https://www.health.ny.gov/health_care/medicaid/publications/docs/adm/00adm7.pdf
  final_url: https://www.health.ny.gov/health_care/medicaid/publications/docs/adm/00adm7.pdf
  status: 200
  content_type: application/pdf
  text_sha256: bd1cc6d3a40ef92f3dc5918e0935b4a350a366e271bdc2d2718813f1b99383ac
  text: ny-adm-00-omm-07/2026-10-07.txt
  raw: ny-adm-00-omm-07/2026-10-07.pdf
