- retrieved: '2026-10-07'
  url: https://hungersolutionsny.org/wp-content/uploads/2023/04/Expanded-Cat-Eligibility-Desk-Guide-9_22_26.pdf
  final_url: https://hungersolutionsny.org/wp-content/uploads/2023/04/Expanded-Cat-Eligibility-Desk-Guide-9_22_26.pdf
  status: 200
  content_type: application/pdf
  text_sha256: 4d6596c99909e4193d289495f3f9807a0853baf5a9769c09f3ac3b021a0e1cf3
  text: hsny-ce-desk-guide-2026-27/2026-10-07.txt
  raw: hsny-ce-desk-guide-2026-27/2026-10-07.pdf
