- retrieved: '2026-10-07'
  url: https://communications.cityofnewyork.us/changes-to-the-snap-sua-policy-for-households-in-receipt-of-heap
  final_url: https://communications.cityofnewyork.us/changes-to-the-snap-sua-policy-for-households-in-receipt-of-heap
  status: 200
  content_type: text/html; charset=utf-8
  text_sha256: c68a7e7598a1dcd2b167e9e02e5ef0cae210859e487996b18dd7318cd4ba6175
  text: ny-dss-heap-sua-notice-2025/2026-10-07.txt
  raw: ny-dss-heap-sua-notice-2025/2026-10-07.html
