- retrieved: '2026-10-07'
  url: https://www.govinfo.gov/content/pkg/USCODE-2023-title42/html/USCODE-2023-title42-chap7-subchapXIX-sec1396d.htm
  final_url: https://www.govinfo.gov/content/pkg/USCODE-2023-title42/html/USCODE-2023-title42-chap7-subchapXIX-sec1396d.htm
  status: 200
  content_type: text/html
  text_sha256: 1c74aac46753bc33b0c9fda7543cdd1da7b22c4f1da0471b1d9ca17fedb1d00e
  text: usc-42-1396d/2026-10-07.txt
  raw: usc-42-1396d/2026-10-07.html
