- retrieved: '2026-10-07'
  url: https://cdss.ca.gov/Portals/9/Additional-Resources/Letters-and-Notices/ACLs/2024/24-59.pdf
  final_url: https://cdss.ca.gov/Portals/9/Additional-Resources/Letters-and-Notices/ACLs/2024/24-59.pdf
  status: 200
  content_type: application/pdf
  text_sha256: 2dbc3e6186dcdd7114e63d1f8b22dcf0d205ff5f1eee00edfee13a5810b4b314
  text: ca-acl-24-59/2026-10-07.txt
  raw: ca-acl-24-59/2026-10-07.pdf
