- retrieved: '2026-10-07'
  url: https://www.ecfr.gov/api/renderer/v1/content/enhanced/current/title-42?part=435&section=435.601
  final_url: https://www.ecfr.gov/api/renderer/v1/content/enhanced/current/title-42?chapter=IV&subchapter=C&part=435&subpart=G&section=435.601
  status: 200
  content_type: text/html; charset=utf-8
  text_sha256: 6a2f97be7970659c4137f691c6789fd3462bbd55ea466317e6b745a3d38576e9
  text: ecfr-42-435-601/2026-10-07.txt
  raw: ecfr-42-435-601/2026-10-07.html
