- retrieved: '2026-10-07'
  url: https://www.law.cornell.edu/regulations/new-york/18-NYCRR-387.24
  final_url: https://www.law.cornell.edu/regulations/new-york/18-NYCRR-387.24
  status: 200
  content_type: text/html; charset=utf-8
  text_sha256: 668b19e7e997fa5d49f3c73d09e0e94298e6bb043cb784fb9c4566b5dc5354dc
  text: ny-nycrr-387-24-lii/2026-10-07.txt
  raw: ny-nycrr-387-24-lii/2026-10-07.html
