- retrieved: '2026-10-07'
  url: https://legislation.nysenate.gov/pdf/laws/ISC3231/
  final_url: https://legislation.nysenate.gov/pdf/laws/ISC3231/
  status: 200
  content_type: application/pdf;charset=utf-8
  text_sha256: b1a753eaf35eb9c7a7332e40705bda48340bc05bd511c6d5fc6f86b57dbf03e4
  text: ny-ins-law-3231/2026-10-07.txt
  raw: ny-ins-law-3231/2026-10-07.pdf
