- retrieved: '2026-10-07'
  url: https://www.cdss.ca.gov/Portals/9/Additional-Resources/Letters-and-Notices/ACLs/2025/25-50.pdf
  final_url: https://www.cdss.ca.gov/Portals/9/Additional-Resources/Letters-and-Notices/ACLs/2025/25-50.pdf
  status: 200
  content_type: application/pdf
  text_sha256: 74ac04922cb7562cadac063f0f305ad66a07d481538136941c1608add4b33a36
  text: ca-acl-25-50/2026-10-07.txt
  raw: ca-acl-25-50/2026-10-07.pdf
