- retrieved: '2026-10-07'
  url: https://www.cdss.ca.gov/Portals/9/Additional-Resources/Letters-and-Notices/ACLs/2025/25-93.pdf
  final_url: https://www.cdss.ca.gov/Portals/9/Additional-Resources/Letters-and-Notices/ACLs/2025/25-93.pdf
  status: 200
  content_type: application/pdf
  text_sha256: 316aafd9c42d8357bb6b62d5a35cca612d42542fe21b5ed8a519346414ce13ca
  text: ca-acl-25-93/2026-10-07.txt
  raw: ca-acl-25-93/2026-10-07.pdf
