/**
 * Known PDF form maps. Keyed by URL. Each field maps a human-readable label
 * (and aliases) to the PDF's exact AcroForm field name — required for PDFs
 * whose field names are mangled by a broken font encoding (e.g. Capitola).
 * Generated by scripts/gen-pdf-forms.ts; do not hand-edit field names.
 */

export interface KnownFormField {
  label: string;
  field: string;
  aliases?: string[];
}

export interface KnownForm {
  url: string;
  title: string;
  fields: KnownFormField[];
}

export const KNOWN_FORMS: KnownForm[] = [
  {
    url: "https://www.cityofcapitola.gov/DocumentCenter/View/212/Scholarship-Application--Spanish",
    title: 'Solicitud de beca de programas juveniles (Capitola Recreation)',
    fields: [
    { label: "Nombre de los padres o tutores", field: "538  259  89 5  589H", aliases: ["parent guardian name", "guardian name"] },
    { label: "Nombre del niño", field: "538 2 4O5H", aliases: ["child name", "student name", "nombre del estudiante"] },
    { label: "Dirección", field: "8Q4H", aliases: ["address", "direccion"] },
    { label: "Estado", field: "95H", aliases: ["state"] },
    { label: "Código postal", field: "6H", aliases: ["C.P.", "CP", "zip", "código postal", "codigo postal"] },
    { label: "Teléfono principal", field: "2 545 68462H", aliases: ["phone", "telefono principal", "primary phone"] },
    { label: "Teléfono secundario", field: "2 545  485H", aliases: ["secondary phone", "telefono secundario"] },
    { label: "Correo electrónico", field: "5885 28Q45H", aliases: ["email", "correo electronico"] },
    { label: "Programa fila 1", field: "03625H 36 652 9954 œ Row1", aliases: ["row 1"] },
    { label: "Programa fila 1 — nombre", field: "œ žRow1", aliases: ["row 1 name"] },
    { label: "Programa fila 1 — campo 3", field: "4 œŸRow1", aliases: ["row 1 field 3"] },
    { label: "Programa fila 2", field: "03625H 36 652 9954 œ Row2", aliases: ["row 2"] },
    { label: "Programa fila 2 — nombre", field: "œ žRow2", aliases: ["row 2 name"] },
    { label: "Programa fila 2 — campo 3", field: "4 œŸRow2", aliases: ["row 2 field 3"] },
    { label: "Programa fila 3", field: "03625H 36 652 9954 œ Row3", aliases: ["row 3"] },
    { label: "Programa fila 3 — nombre", field: "œ žRow3", aliases: ["row 3 name"] },
    { label: "Programa fila 3 — campo 3", field: "4 œŸRow3", aliases: ["row 3 field 3"] },
    { label: "Programa fila 4", field: "03625H 36 652 9954 œ Row4", aliases: ["row 4"] },
    { label: "Programa fila 4 — nombre", field: "œ žRow4", aliases: ["row 4 name"] },
    { label: "Programa fila 4 — campo 3", field: "4 œŸRow4", aliases: ["row 4 field 3"] },
    { label: "Programa fila 5", field: "03625H 36 652 9954 œ Row5", aliases: ["row 5"] },
    { label: "Programa fila 5 — nombre", field: "œ žRow5", aliases: ["row 5 name"] },
    { label: "Programa fila 5 — campo 3", field: "4 œŸRow5", aliases: ["row 5 field 3"] },
    { label: "Programa fila 6", field: "03625H 36 652 9954 œ Row6", aliases: ["row 6"] },
    { label: "Programa fila 6 — nombre", field: "œ žRow6", aliases: ["row 6 name"] },
    { label: "Programa fila 6 — campo 3", field: "4 œŸRow6", aliases: ["row 6 field 3"] },
    { label: "Ingresos mensuales de la familia", field: "48959 34929  2 32 P59 29 49  48959QH", aliases: ["ingresos mensuales", "monthly income"] },
    { label: "Total de gastos mensuales", field: "52  959 34929H", aliases: ["gastos mensuales", "monthly expenses"] },
    { label: "Firma", field: "Signature1", aliases: ["signature"] },
    { label: "Fecha", field: "Date2_af_date", aliases: ["date"] },
    ],
  },
];

/** Return the known-form map for a URL, if one is registered. */
export function findForm(url: string): KnownForm | undefined {
  return KNOWN_FORMS.find((f) => f.url === url);
}
