- retrieved: '2026-10-07'
  url: https://www.dhs.state.il.us/page.aspx?item=56693
  final_url: https://www.dhs.state.il.us/page.aspx?item=56693
  status: 200
  content_type: text/html; charset=utf-8
  text_sha256: 744979bd87b956101236304008ba5eeddbe22a7ae9e2a70c85432fbbaecb36dd
  text: il-dhs-pm-11-02-07-e/2026-10-07.txt
  raw: il-dhs-pm-11-02-07-e/2026-10-07.html
