- retrieved: '2026-10-07'
  url: https://www.cdss.ca.gov/Portals/9/Additional-Resources/Letters-and-Notices/ACLs/2025/25-68.pdf
  final_url: https://www.cdss.ca.gov/Portals/9/Additional-Resources/Letters-and-Notices/ACLs/2025/25-68.pdf
  status: 200
  content_type: application/pdf
  text_sha256: be45b776dfec42f0db66a1ed819eb983ba48b7f2491d3b2fcaf2965d403ea0bd
  text: ca-acl-25-68/2026-10-07.txt
  raw: ca-acl-25-68/2026-10-07.pdf
