- retrieved: '2026-10-07'
  url: https://www.cdss.ca.gov/Portals/9/Additional-Resources/Letters-and-Notices/ACLs/2026/26-58.pdf
  final_url: https://www.cdss.ca.gov/Portals/9/Additional-Resources/Letters-and-Notices/ACLs/2026/26-58.pdf
  status: 200
  content_type: application/pdf
  text_sha256: 2d84be1ea34d9601d1ecb88f2142cd796ff650cd8be0a465db7b42f6537a5c52
  text: ca-acl-26-58/2026-10-07.txt
  raw: ca-acl-26-58/2026-10-07.pdf
