- retrieved: '2026-10-07'
  url: https://snapguideny.org/budgeting-estimating-snap-benefits/calculating-deductions/
  final_url: https://snapguideny.org/budgeting-estimating-snap-benefits/calculating-deductions/
  status: 200
  content_type: text/html; charset=utf-8
  text_sha256: 7718bbfef82247be54f10e26a833d91f6fd507a4626115d411745e10b08f0a19
  text: hsny-snapguide-deductions/2026-10-07.txt
  raw: hsny-snapguide-deductions/2026-10-07.html
