- retrieved: '2026-10-07'
  url: https://healthyschoolscampaign.org/blog/illinois-must-step-up-and-meet-its-obligation-to-fund-free-school-meals-for-all-public-school-students/
  final_url: https://healthyschoolscampaign.org/blog/illinois-must-step-up-and-meet-its-obligation-to-fund-free-school-meals-for-all-public-school-students/
  status: 200
  content_type: text/html; charset=utf-8
  text_sha256: 1bcb30851e6860ef6657f0d20c18e0f12911897a2e855dcf833ef506e069277e
  text: il-hsc-hsmfa-blog/2026-10-07.txt
  raw: il-hsc-hsmfa-blog/2026-10-07.html
