- retrieved: '2026-10-07'
  url: https://www.law.cornell.edu/regulations/new-york/18-NYCRR-398-1.1
  final_url: https://www.law.cornell.edu/regulations/new-york/18-NYCRR-398-1.1
  status: 200
  content_type: text/html; charset=utf-8
  text_sha256: 58493dfd8768a54cac9b5fc647a6e18d67a929afbab2ea07c75e6244184b65de
  text: ny-nycrr-398-1-1-lii/2026-10-07.txt
  raw: ny-nycrr-398-1-1-lii/2026-10-07.html
