- retrieved: '2026-10-07'
  url: https://www.ecfr.gov/api/renderer/v1/content/enhanced/current/title-42?part=435&section=435.4
  final_url: https://www.ecfr.gov/api/renderer/v1/content/enhanced/current/title-42?chapter=IV&subchapter=C&part=435&subpart=A&section=435.4
  status: 200
  content_type: text/html; charset=utf-8
  text_sha256: e4f03a885229a3534deb9b7060803777096fd1a46e5349138c41782ac78c0454
  text: ecfr-42-435-4/2026-10-07.txt
  raw: ecfr-42-435-4/2026-10-07.html
