- retrieved: '2026-10-07'
  url: https://healthconsumer.org/wp/wp-content/uploads/2026/03/Asset-Limits-Practice-Tip-12-2025-March-2026-Update.pdf
  final_url: https://healthconsumer.org/wp/wp-content/uploads/2026/03/Asset-Limits-Practice-Tip-12-2025-March-2026-Update.pdf
  status: 200
  content_type: application/pdf
  text_sha256: f1bd1522d6f49e2e375258d048c200fc36501c7da786d41dd1742e0f6e56263c
  text: ca-hca-asset-limits-practice-tip-2026/2026-10-07.txt
  raw: ca-hca-asset-limits-practice-tip-2026/2026-10-07.pdf
