import { listPdfFieldsBytes } from '../src/integrations/pdf.js';
import { writeFile } from 'node:fs/promises';

/**
 * Regenerate `src/integrations/pdf-forms.ts` from the live Capitola PDF so the
 * field names are byte-exact (they contain special chars / odd spacing). Run
 * whenever the city updates the PDF and the field order/names change.
 */

const URL = 'https://www.cityofcapitola.gov/DocumentCenter/View/212/Scholarship-Application--Spanish';

// Semantic labels in DOCUMENT ORDER (matches form.getFields() order).
// [label, ...aliases]
const LABELS: Array<[string, ...string[]]> = [
  ['Nombre de los padres o tutores', 'parent guardian name', 'guardian name'],
  ['Nombre del niño', 'child name', 'student name', 'nombre del estudiante'],
  ['Dirección', 'address', 'direccion'],
  ['Estado', 'state'],
  ['Código postal', 'C.P.', 'CP', 'zip', 'código postal', 'codigo postal'],
  ['Teléfono principal', 'phone', 'telefono principal', 'primary phone'],
  ['Teléfono secundario', 'secondary phone', 'telefono secundario'],
  ['Correo electrónico', 'email', 'correo electronico'],
  ['Programa fila 1', 'row 1'],
  ['Programa fila 1 — nombre', 'row 1 name'],
  ['Programa fila 1 — campo 3', 'row 1 field 3'],
  ['Programa fila 2', 'row 2'],
  ['Programa fila 2 — nombre', 'row 2 name'],
  ['Programa fila 2 — campo 3', 'row 2 field 3'],
  ['Programa fila 3', 'row 3'],
  ['Programa fila 3 — nombre', 'row 3 name'],
  ['Programa fila 3 — campo 3', 'row 3 field 3'],
  ['Programa fila 4', 'row 4'],
  ['Programa fila 4 — nombre', 'row 4 name'],
  ['Programa fila 4 — campo 3', 'row 4 field 3'],
  ['Programa fila 5', 'row 5'],
  ['Programa fila 5 — nombre', 'row 5 name'],
  ['Programa fila 5 — campo 3', 'row 5 field 3'],
  ['Programa fila 6', 'row 6'],
  ['Programa fila 6 — nombre', 'row 6 name'],
  ['Programa fila 6 — campo 3', 'row 6 field 3'],
  ['Ingresos mensuales de la familia', 'ingresos mensuales', 'monthly income'],
  ['Total de gastos mensuales', 'gastos mensuales', 'monthly expenses'],
  ['Firma', 'signature'],
  ['Fecha', 'date'],
];

async function main(): Promise<void> {
  const res = await fetch(URL);
  if (!res.ok) throw new Error(`fetch ${res.status}`);
  const buf = new Uint8Array(await res.arrayBuffer());
  const r = await listPdfFieldsBytes(buf);
  if (!r.ok || !r.data) throw new Error(r.reason ?? 'list failed');
  const names = r.data.fields.map((f) => f.name);
  if (names.length !== LABELS.length) {
    throw new Error(`field count drift: got ${names.length}, expected ${LABELS.length}`);
  }

  const lines = LABELS.map(([label, ...aliases], i) => {
    const name = names[i]!;
    const aliasPart = aliases.length
      ? `, aliases: [${aliases.map((a) => JSON.stringify(a)).join(', ')}]`
      : '';
    return `    { label: ${JSON.stringify(label)}, field: ${JSON.stringify(name)}${aliasPart} },`;
  }).join('\n');

  const out = `/**
 * Known PDF form maps. Keyed by URL. Each field maps a human-readable label
 * (and aliases) to the PDF's exact AcroForm field name — required for PDFs
 * whose field names are mangled by a broken font encoding (e.g. Capitola).
 * Generated by scripts/gen-pdf-forms.ts; do not hand-edit field names.
 */

export interface KnownFormField {
  label: string;
  field: string;
  aliases?: string[];
}

export interface KnownForm {
  url: string;
  title: string;
  fields: KnownFormField[];
}

export const KNOWN_FORMS: KnownForm[] = [
  {
    url: ${JSON.stringify(URL)},
    title: 'Solicitud de beca de programas juveniles (Capitola Recreation)',
    fields: [
${lines}
    ],
  },
];

/** Return the known-form map for a URL, if one is registered. */
export function findForm(url: string): KnownForm | undefined {
  return KNOWN_FORMS.find((f) => f.url === url);
}
`;

  await writeFile('src/integrations/pdf-forms.ts', out, 'utf8');
  console.log(`Wrote src/integrations/pdf-forms.ts with ${names.length} fields.`);
}

main().catch((e) => {
  console.error('FAIL', e);
  process.exit(1);
});
