- retrieved: '2026-10-07'
  url: https://stgenssa.sccgov.org/debs/program_handbooks/medi-cal/assets/14MAGIMCTax/Work_and_Community_Engagement_Requirement.htm
  final_url: https://stgenssa.sccgov.org/debs/program_handbooks/medi-cal/assets/14MAGIMCTax/Work_and_Community_Engagement_Requirement.htm
  status: 200
  content_type: text/html
  text_sha256: ada7b0ff7257cc1526fdd8c01d48a201bdf959a62de5e0f47c2008c46ccbf63f
  text: ca-scc-mc-wcer/2026-10-07.txt
  raw: ca-scc-mc-wcer/2026-10-07.html
