- retrieved: '2026-10-07'
  url: https://www.law.cornell.edu/regulations/new-york/18-NYCRR-398-4.1
  final_url: https://www.law.cornell.edu/regulations/new-york/18-NYCRR-398-4.1
  status: 200
  content_type: text/html; charset=utf-8
  text_sha256: 1fcb3e62e2c0a47332009661ae37d7040ebd1fbd7220973c321784410d1bc37e
  text: ny-nycrr-398-4-1-lii/2026-10-07.txt
  raw: ny-nycrr-398-4-1-lii/2026-10-07.html
