- retrieved: '2026-10-07'
  url: https://www.cdss.ca.gov/Portals/9/Additional-Resources/Letters-and-Notices/ACINs/2025/I-46_25.pdf
  final_url: https://www.cdss.ca.gov/Portals/9/Additional-Resources/Letters-and-Notices/ACINs/2025/I-46_25.pdf
  status: 200
  content_type: application/pdf
  text_sha256: af6108ad2dcb90fad9f2cce3bc6c1e99325d7e269e3edfeb5ba14a52b4862a3e
  text: ca-acin-i-46-25/2026-10-07.txt
  raw: ca-acin-i-46-25/2026-10-07.pdf
