- retrieved: '2026-10-07'
  url: https://stgenssa.sccgov.org/debs/program_handbooks/medi-cal/assets/21Property/PropertyLimits.htm
  final_url: https://stgenssa.sccgov.org/debs/program_handbooks/medi-cal/assets/21Property/PropertyLimits.htm
  status: 200
  content_type: text/html
  text_sha256: 84e2995e66fd9750f0c2d1984f3fb44cb8b2ff81355a2fef3b1b9abe661bc74b
  text: ca-scc-mc-property-limits/2026-10-07.txt
  raw: ca-scc-mc-property-limits/2026-10-07.html
