// Two-color textbook style: black ink plus one spot color (and its tints).
// Used by every packet. Packets are generated by adaptcalc/render.py.

#let spot = rgb("#006B7F")          // the second ink
#let tint1 = spot.lighten(86%)      // screens of the spot color
#let tint2 = spot.lighten(93%)
#let ink = black
#let sans = ("Fira Sans",)
#let serif = ("Libertinus Serif",)

#let book(
  title: none, running: none, code: none, attribution: none,
  kicker: [#smallcaps[Chapter 2] #h(0.4em) #text(fill: black)[Limits]], body,
) = {
  set document(title: title)
  set page(
    paper: "us-letter",
    margin: (top: 0.95in, bottom: 0.9in, inside: 0.95in, outside: 1.05in),
    header: context {
      let n = counter(page).get().first()
      if n > 1 {
        set text(font: sans, size: 8pt, fill: spot)
        grid(columns: (1fr, auto),
          kicker,
          [#running #h(0.6em) #box(fill: spot, inset: (x: 4pt, y: 2pt), text(fill: white, weight: "bold", code))])
        v(-4pt)
        line(length: 100%, stroke: 0.5pt + spot)
      }
    },
    footer: context {
      set text(font: sans, size: 8.5pt)
      let n = counter(page).get().first()
      let even = calc.even(n)
      grid(columns: (1fr, 1fr),
        align(left, if even { text(fill: spot, weight: "bold", str(n)) } else { text(size: 7pt, fill: luma(90), attribution) }),
        align(right, if even { text(size: 7pt, fill: luma(90), attribution) } else { text(fill: spot, weight: "bold", str(n)) }))
    },
  )
  set text(font: serif, size: 10.5pt, fill: ink, hyphenate: false, lang: "en")
  set par(justify: true, leading: 0.62em, spacing: 0.95em)
  show math.equation: set text(font: "New Computer Modern Math")
  set list(marker: text(fill: spot)[•], indent: 0.6em)
  set enum(indent: 0.4em)
  set table(stroke: 0.5pt + spot.lighten(40%))
  body
}

#let section-head(num, title) = {
  v(0.6em)
  block(width: 100%, below: 0.9em)[
    #set text(font: sans)
    #grid(columns: (auto, 1fr), column-gutter: 10pt, align: bottom,
      text(size: 24pt, weight: "bold", fill: spot, num),
      text(size: 19pt, weight: "semibold", title))
    #v(-6pt)
    #line(length: 100%, stroke: 1.4pt + spot)
  ]
}

#let subsection(title) = block(above: 1.3em, below: 0.7em, sticky: true,
  text(font: sans, size: 13pt, weight: "semibold", fill: spot, title))

#let objectives(items) = block(width: 100%, fill: tint2, stroke: (top: 2.5pt + spot), inset: 10pt, below: 1.1em)[
  #text(font: sans, size: 8.5pt, weight: "bold", fill: spot, tracking: 0.08em)[LEARNING OBJECTIVES]
  #v(-2pt)
  #set text(size: 10pt)
  #text(font: sans, size: 9pt)[By the end of this section, you will be able to:]
  #list(..items)
]

#let definition(title, body) = block(width: 100%, breakable: true, inset: (left: 11pt, rest: 8pt),
  stroke: (left: 3pt + spot), below: 1em)[
  #text(font: sans, size: 9.5pt, weight: "bold", fill: spot, tracking: 0.04em, title)
  #v(-3pt)
  #body
]

#let theorem(title, body) = block(width: 100%, breakable: true, fill: tint1, inset: 10pt, radius: 2pt, below: 1em)[
  #text(font: sans, size: 9pt, weight: "bold", fill: spot, tracking: 0.06em)[THEOREM]
  #h(0.4em) #text(font: sans, size: 10pt, weight: "semibold", title)
  #v(-3pt)
  #body
]

#let strategy(title, body) = block(width: 100%, breakable: true, stroke: 1pt + spot, radius: 2pt, below: 1em, clip: false)[
  #block(width: 100%, fill: spot, inset: (x: 10pt, y: 5pt), below: 0pt,
    text(font: sans, size: 9.5pt, weight: "semibold", fill: white)[Problem-Solving Strategy: #title])
  #block(inset: 10pt, body)
]

#let howto(title, body) = block(width: 100%, breakable: true, stroke: 1pt + spot, radius: 2pt, below: 1em)[
  #block(width: 100%, fill: tint1, inset: (x: 10pt, y: 5pt), below: 0pt,
    [#text(font: sans, size: 8.5pt, weight: "bold", fill: spot, tracking: 0.08em)[HOW TO] #h(0.4em) #text(font: sans, size: 9.5pt, weight: "semibold", title)])
  #block(inset: 10pt, body)
]

#let qa(body) = block(width: 100%, breakable: true, fill: tint2, inset: 9pt, below: 1em)[
  #text(font: sans, size: 8.5pt, weight: "bold", fill: spot, tracking: 0.08em)[Q & A]
  #v(-3pt)
  #body
]

#let note-box(title, body) = block(width: 100%, breakable: true, stroke: (y: 0.6pt + spot), inset: (y: 8pt), below: 1em)[
  #if title != none [#text(font: sans, size: 9pt, weight: "bold", fill: spot, title) \ ]
  #body
]

#let example(label, title, problem, solution, after) = block(width: 100%, breakable: true, below: 1.1em)[
  #block(width: 100%, stroke: (bottom: 1pt + spot), inset: (bottom: 4pt), below: 0.6em, sticky: true)[
    #box(fill: spot, inset: (x: 6pt, y: 3pt), text(font: sans, size: 9pt, weight: "bold", fill: white, tracking: 0.06em, upper(label)))
    #h(6pt) #text(font: sans, size: 11pt, weight: "semibold", fill: spot, title)
  ]
  #problem
  #block(above: 0.8em, below: 0.5em, sticky: true, text(font: sans, size: 9.5pt, weight: "bold", fill: spot)[Solution])
  #solution
  #after
  #v(-4pt)
  #line(length: 100%, stroke: 0.5pt + spot)
]

#let checkpoint(label, body) = block(width: 100%, breakable: true, fill: tint2, inset: 9pt, below: 1em)[
  #box(width: 7pt, height: 7pt, fill: spot) #h(3pt)
  #text(font: sans, size: 9pt, weight: "bold", fill: spot, tracking: 0.06em, upper(label))
  #v(-3pt)
  #body
]

#let fig(images, label, caption) = figure(
  kind: "book-figure", supplement: none, numbering: none,
  block(width: 100%, {
    set align(center)
    for img in images { img }
  }),
  caption: if caption != none or label != none {
    set align(left)
    set text(size: 9pt)
    if label != none [#text(font: sans, weight: "bold", fill: spot, label) #h(0.3em)]
    caption
  },
)
#show figure.caption: it => it.body

#let transition(body) = block(width: 100%, inset: (left: 10pt, y: 4pt), below: 1em,
  stroke: (left: (paint: spot, thickness: 1pt, dash: "dashed")))[
  #set text(font: sans, size: 9.2pt, style: "italic", fill: luma(35))
  #body
]

#let practice-head(title) = block(above: 1.4em, below: 0.8em, sticky: true)[
  #box(fill: spot, inset: (x: 8pt, y: 4pt), text(font: sans, size: 11pt, weight: "bold", fill: white, title))
  #h(1fr)
]

#let problem(num, body, space: 6, figure: none, tag: none, given: none) = block(width: 100%, breakable: false, below: 0.4em)[
  #grid(columns: (1.7em, 1fr), column-gutter: 4pt,
    text(font: sans, weight: "bold", fill: spot, str(num) + "."),
    [#if tag != none [#box(stroke: 0.6pt + spot, inset: (x: 3pt, y: 1.5pt), radius: 1pt,
        text(font: sans, size: 7pt, weight: "bold", fill: spot, tracking: 0.08em, upper(tag))) #h(4pt)]
     #body #if figure != none { v(2pt); figure }
     #if given != none {
       v(3pt)
       block(width: 100%, fill: tint2, inset: (x: 9pt, y: 7pt), stroke: (left: 2pt + spot))[
         #text(font: sans, size: 8pt, weight: "bold", fill: spot, tracking: 0.06em)[THE FIRST STEPS ARE DONE. FINISH THE SOLUTION.]
         #v(-2pt)
         #for line in given { block(above: 0.5em, below: 0.5em, line) }
       ]
     }])
  #v(space * 1.35em)
]

// A worked solution in the answer key: the problem number, then one line per step.
#let worked(num, lines) = block(width: 100%, breakable: false, below: 0.8em)[
  #grid(columns: (1.7em, 1fr), column-gutter: 4pt,
    text(font: sans, weight: "bold", fill: spot, str(num) + "."),
    stack(spacing: 0.55em, ..lines))
]

// A fixed self-explanation prompt after a worked example (not generated text).
#let pause(body) = block(width: 100%, inset: (left: 10pt, y: 5pt), below: 1em,
  stroke: (left: 2pt + spot))[
  #text(font: sans, size: 8pt, weight: "bold", fill: spot, tracking: 0.08em)[PAUSE AND EXPLAIN] #h(4pt)
  #set text(size: 10pt, style: "italic")
  #body
]

// Ungraded writing prompt at the end of a lesson.
#let explain(body) = block(width: 100%, above: 1.2em, below: 0.6em, stroke: 0.6pt + spot, inset: 10pt, radius: 2pt)[
  #text(font: sans, size: 8.5pt, weight: "bold", fill: spot, tracking: 0.08em)[IN YOUR OWN WORDS]
  #v(-3pt)
  #set text(size: 10pt)
  #body
  #v(5.5em)
]

#let instructions(body) = block(width: 100%, stroke: 1pt + spot, inset: 10pt, radius: 2pt, below: 1.2em)[
  #text(font: sans, size: 9pt, weight: "bold", fill: spot, tracking: 0.06em)[HOW TO WRITE YOUR WORK]
  #v(-2pt)
  #set text(font: sans, size: 9.2pt)
  #body
]

// The next part of the child's own story, under the heading of a set of pages (no math in it).
#let story(head, title, body, aloud: false) = block(width: 100%, below: 1.3em, inset: (x: 14pt, y: 11pt),
  fill: rgb("#f7f2e6"), stroke: (top: 0.8pt + spot, bottom: 0.8pt + spot))[
  #set par(justify: false, leading: 0.68em)
  #text(font: sans, size: 7.5pt, weight: "bold", fill: spot, tracking: 0.12em, upper(head))
  #if aloud [#h(1fr) #text(font: sans, size: 7.5pt, fill: luma(90), tracking: 0.08em)[READ IT TOGETHER]]
  #v(-5pt)
  #text(size: 14pt, style: "italic", weight: "bold", title)
  #v(-3pt)
  #set text(size: if aloud { 12.5pt } else { 11pt })
  #body
  #v(-2pt)
  #align(right, text(font: sans, size: 7.5pt, style: "italic", fill: luma(90))[The story goes on in the next pages, once these are done.])
]

#let cover(kicker, title, subtitle, code, qr: none, scan-note: none) = block(width: 100%, below: 1.4em)[
  #set par(justify: false)
  #grid(columns: (1fr, auto), align: horizon, column-gutter: 14pt,
    [#text(font: sans, size: 9pt, weight: "bold", fill: spot, tracking: 0.12em, upper(kicker))
     #v(-6pt)
     #text(font: sans, size: 22pt, weight: "bold", title)
     #v(-8pt)
     #text(font: sans, size: 11pt, fill: luma(60), subtitle)],
    if qr != none {
      // grown-ups scan this with a phone camera when the pages are done: no codes, no typing
      box(stroke: 1.2pt + spot, inset: 6pt, radius: 3pt, grid(columns: (auto, 1.25in), column-gutter: 7pt, align: horizon,
        image(qr, width: 0.82in),
        [#set par(leading: 0.45em)
         #text(font: sans, size: 7.5pt, weight: "bold", fill: spot)[GROWN-UPS] \
         #text(font: sans, size: 7.5pt, scan-note) \
         #text(font: sans, size: 6.5pt, fill: luma(110))[Pages #code]]))
    } else {
      box(stroke: 2pt + spot, inset: 8pt, radius: 3pt,
        align(center)[#text(font: sans, size: 7.5pt, fill: spot, weight: "bold")[WRITE THIS CODE ON YOUR PAGE] \
        #text(font: sans, size: 26pt, weight: "bold", fill: spot, code)])
    })
  #line(length: 100%, stroke: 2pt + spot)
]
