- retrieved: '2026-10-07'
  url: https://www.law.cornell.edu/regulations/new-york/18-NYCRR-387.26
  final_url: https://www.law.cornell.edu/regulations/new-york/18-NYCRR-387.26
  status: 200
  content_type: text/html; charset=utf-8
  text_sha256: 026097cea7b7ecf55b3b16d71cfc0beb27d5ba7636e997bae94740c3a2d2d981
  text: ny-nycrr-387-26-lii/2026-10-07.txt
  raw: ny-nycrr-387-26-lii/2026-10-07.html
