- retrieved: '2026-10-07'
  url: https://www.khalsalaw.com/2026/04/01/updated-guidance-for-2026-ny-community-medicaid/
  final_url: https://www.khalsalaw.com/2026/04/01/updated-guidance-for-2026-ny-community-medicaid/
  status: 200
  content_type: text/html; charset=utf-8
  text_sha256: d1fe5c8713d6675bc97f938b52908fdb00de2d389020c653802fcd5b9517f8f2
  text: khalsalaw-2026-ny-community-medicaid/2026-10-07.txt
  raw: khalsalaw-2026-ny-community-medicaid/2026-10-07.html
