- retrieved: '2026-10-07'
  url: https://www.govinfo.gov/content/pkg/USCODE-2023-title42/html/USCODE-2023-title42-chap7-subchapII-sec426.htm
  final_url: https://www.govinfo.gov/content/pkg/USCODE-2023-title42/html/USCODE-2023-title42-chap7-subchapII-sec426.htm
  status: 200
  content_type: text/html
  text_sha256: 39c93544251368c7cb4ef86916acba63b41efde0d6dab97d76e90d734801bc21
  text: usc-42-426/2026-10-07.txt
  raw: usc-42-426/2026-10-07.html
