- retrieved: '2026-10-07'
  url: https://www.ecfr.gov/api/renderer/v1/content/enhanced/current/title-7?part=273&section=273.9
  final_url: https://www.ecfr.gov/api/renderer/v1/content/enhanced/current/title-7?subtitle=B&chapter=II&subchapter=C&part=273&subpart=D&section=273.9
  status: 200
  content_type: text/html; charset=utf-8
  text_sha256: badaecb6da03e6508e589db2ff8f94f668e6765b7a5186f7715ec418846c4591
  text: ecfr-7-273-9/2026-10-07.txt
  raw: ecfr-7-273-9/2026-10-07.html
